### ISSUE TITLE
Chunk size metadata

### ISSUE THREAD

**Issue by tilsche** [tud-zih-energy/lmgd#4]
See https://github.com/metricq/metricq-python/issues/65

**Comment by bmario** [comment]
IIRC in gapless mode, the LMG670 sends chunks with slightly different sizes, what do we do in those cases? While the documentation says that the type of the `chunkSize` metadata is `Number`, so technically speaking, I could use a float to denote an average. But, the documentation also says that for varying chunk size, `None` should be used.

**Comment by tilsche** [comment]
I don't see why not to adhere to the documentation.
